### ISSUE TITLE
Add extra points in extra classes in utube

### ISSUE THREAD

**Issue by Anitha1122** [Anithakumaresan15/Instagrams#1]
Dear AnithaKumaresan15,
  add extra points in that file
Thank you
Regards
Anitha1122

**Comment by Anithakumaresan15** [comment]
Dear Anitha1122
We have added extra points 
Thank you
Regards 
Anithakumaresan15

**Comment by Anithakumaresan15** [comment]
Dear Anitha1122'
   Thank you for suggesting to add extra points, we have added that points. Keep supporting us

Regards
Anitha15
